name: push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v2
	with:
	  ref: master

      - name: push gh-pages
        env:
  	  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
	run: |
	  git push origin gh-pages
