name: push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: push gh-pages
        run: |
          git switch gh-pages
          git fetch && git pull origin master
          rm ./docs/*
          cp *.* ./docs/
          git add .
          git commit -m "update gh-pages"
          git push origin gh-pages
