name: push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@master
      - name: git setting
        run: |
         git config --local user.email "workflow@exsample.com"
         git config --local user.name "workflow[bot]"
      - name: update docs
        run: |
          rm ./docs/*
          cp *.md ./docs/
          ls *.md
      - name: commit docs
        run: |
          date >> README.md
          git add .
          git commit -m "update docs"
          git push origin master
