name: push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@master
      - name: git setting
        run: |
         git config --local user.email "s.yokoyama.rss@gmail.com"
         git config --local user.name "seyokoyama"
      - name: update docs
        run: |
          rm ./docs/*
          cp *.* ./docs/
          git add .
          git commit -m "update docs"
          git push origin master
