name: push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: update docs
        run: |
          rm ./docs/*
          cp *.* ./docs/
          git add .
          git config --global user.email "ci@exsample.com"
          git config --global user.name "ci"
          git commit -m "update docs"
          git push origin master
